version: "3.9"

services:

  # ==============================
  # PostgreSQL Database
  # ==============================
  db:
    image: postgres:15
    container_name: hotel_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: Hotel_Room_Booking_System
      POSTGRES_USER: shamil
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shamil -d Hotel_Room_Booking_System"]
      interval: 5s
      timeout: 5s
      retries: 5


  # ==============================
  # Django Backend
  # ==============================
  backend:
    build:
      context: ./Backend/src/HRBS
      dockerfile: Dockerfile
    container_name: hotel_backend
    restart: unless-stopped

    command: >
      sh -c "
      python manage.py migrate &&
      gunicorn HRBS.wsgi:application --bind 0.0.0.0:8000
      "

    volumes:
      - ./Backend/src/HRBS:/app
      - media_volume:/app/media

    ports:
      - "8000:8000"

    depends_on:
      db:
        condition: service_healthy

    environment:
      DB_NAME: Hotel_Room_Booking_System
      DB_USER: shamil
      DB_PASSWORD: 1234
      DB_HOST: db
      DB_PORT: 5432

  frontend:
    build:
      context: ./frontend/HRBS_Frontend
    container_name: hotel_frontend
    volumes:
      - ./frontend/HRBS_Frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"   # or 3000:3000 for CRA
    depends_on:
      - backend

volumes:
  postgres_data:
  media_volume: